const colors = {
  light: {
    text: "#0F172A",
    tint: "#2563EB",
    background: "#F8FAFC",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#DBEAFE",
    secondaryForeground: "#1E40AF",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#DBEAFE",
    accentForeground: "#1E3A8A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#E2E8F0",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
  },

  // Dark palette — deep navy / slate tones
  dark: {
    text: "#E2E8F0",
    tint: "#3B82F6",
    background: "#0A0F1E",
    foreground: "#E2E8F0",
    card: "#111827",
    cardForeground: "#E2E8F0",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#1E3A8A",
    secondaryForeground: "#93C5FD",
    muted: "#1E293B",
    mutedForeground: "#64748B",
    accent: "#1D4ED8",
    accentForeground: "#DBEAFE",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    border: "#1E293B",
    input: "#1E293B",
    success: "#4ADE80",
    successForeground: "#FFFFFF",
    warning: "#FCD34D",
    warningForeground: "#0F172A",
  },

  radius: 16,
};

export default colors;
