const colors = {
  light: {
    text: "#1A0F0A",
    tint: "#D4500A",
    background: "#FFF8F3",
    foreground: "#1A0F0A",
    card: "#FFFFFF",
    cardForeground: "#1A0F0A",
    primary: "#D4500A",
    primaryForeground: "#FFFFFF",
    secondary: "#FEF0E7",
    secondaryForeground: "#7A3F1E",
    muted: "#F7EDE6",
    mutedForeground: "#9B7B68",
    accent: "#F4A261",
    accentForeground: "#1A0F0A",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#EDE0D8",
    input: "#EDE0D8",
    success: "#16A34A",
    successForeground: "#FFFFFF",
    warning: "#D97706",
    warningForeground: "#FFFFFF",
  },

  // Full dark-mode palette — warm charcoal, not cold grey
  dark: {
    text: "#F2E8E0",
    tint: "#E8622A",
    background: "#100804",
    foreground: "#F2E8E0",
    card: "#1C1008",
    cardForeground: "#F2E8E0",
    primary: "#E8622A",
    primaryForeground: "#FFFFFF",
    secondary: "#2E1A0E",
    secondaryForeground: "#D4956A",
    muted: "#2A1610",
    mutedForeground: "#8A6A58",
    accent: "#C47042",
    accentForeground: "#F2E8E0",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    border: "#3A2015",
    input: "#3A2015",
    success: "#4ADE80",
    successForeground: "#FFFFFF",
    warning: "#FCD34D",
    warningForeground: "#1A0F0A",
  },

  radius: 12,
};

export default colors;
